version: 2
updates:
# Dependabot will automatically update npm packages
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - adamwathan
  assignees:
    - adamwathan
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Dependabot will automatically update packages in GitHub actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - adamwathan
  assignees:
    - adamwathan
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
